### ISSUE TITLE
phpctags: Plz update composer and recreate phar

### ISSUE THREAD

**Issue by 3ynm** [xcwen/ac-php#151]
I was having the following error while running ac-php-remake-tags with PHP 8.1.

```
[DEBUG]: PHP Warning:  Undefined array key 403 in phar:///home/me/.emacs.d/elpa/ac-php-core-20220120.754/phpctags/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 323
[DEBUG]: PHP Fatal error:  Uncaught TypeError: PhpParser\Lexer::getNextToken(): Return value must be of type int, null returned in phar:///home/me/.emacs.d/elpa/ac-php-core-20220120.754/phpctags/vendor/nikic/php-parser/lib/PhpParser/Lexer.php:364
[DEBUG]: Stack trace:
[DEBUG]: #0 phar:///home/me/.emacs.d/elpa/ac-php-core-20220120.754/phpctags/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(209): PhpParser\Lexer->getNextToken()
[DEBUG]: #1 phar:///home/me/.emacs.d/elpa/ac-php-core-20220120.754/phpctags/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(159): PhpParser\ParserAbstract->doParse()
[DEBUG]: #2 phar:///home/me/.emacs.d/elpa/ac-php-core-20220120.754/phpctags/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(51): PhpParser\ParserAbstract->parse()
[DEBUG]: #3 phar:///home/me/.emacs.d/elpa/ac-php-core-20220120.754/phpctags/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(32): PhpParser\Parser\Multiple->tryParse()
[DEBUG]: #4 phar:///home/me/.emacs.d/elpa/ac-php-core-20220120.754/phpctags/PHPCtags.class.php(633): PhpParser\Parser\Multiple->parse()
[DEBUG]: #5 phar:///home/me/.emacs.d/elpa/ac-php-core-20220120.754/phpctags/deal_config.php(250): PHPCtags->process_single_file()
[DEBUG]: #6 phar:///home/me/.emacs.d/elpa/ac-php-core-20220120.754/phpctags/deal_config.php(356): deal_file_tags()
[DEBUG]: #7 phar:///home/me/.emacs.d/elpa/ac-php-core-20220120.754/phpctags/bootstrap.php(260): deal_config()
[DEBUG]: #8 /home/me/.emacs.d/elpa/ac-php-core-20220120.754/phpctags(10): include('...')
[DEBUG]: #9 {main}
[DEBUG]:   thrown in phar:///home/me/.emacs.d/elpa/ac-php-core-20220120.754/phpctags/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 364
[DEBUG]: 
ac-php: Something went wrong
ac-php: The re-indexing process exited abnormally
ac-php: Please re-check for incorrect syntax and possible PHP errors and try again later
[DEBUG]: exited abnormally with code 255
```
I've recreated the phpctags phar after updating composer dependencies and it works flawlessly.

**Comment by xcwen** [comment]
retest
