### ISSUE TITLE
Can't find php files in cakephp project

### ISSUE THREAD

**Issue by tasuwo** [xcwen/ac-php#37]
I develop on CakePHP, so I have a need for code completion of cakephp's core code by ac-php. I assume that cakephp's core code located `vendor/cakephp/cakephp/src`. A part of the directory is following.

``` shell
.
├── Auth
│   ├── AbstractPasswordHasher.php
│   ├── BaseAuthenticate.php
│   ├── BaseAuthorize.php
│   ├── BasicAuthenticate.php
│   ├── ControllerAuthorize.php
│   ├── DefaultPasswordHasher.php
│   ├── DigestAuthenticate.php
│   ├── FallbackPasswordHasher.php
│   ├── FormAuthenticate.php
│   ├── PasswordHasherFactory.php
│   ├── Storage
│   │   ├── MemoryStorage.php
│   │   ├── SessionStorage.php
│   │   └── StorageInterface.php
│   └── WeakPasswordHasher.php
├── Cache
│   ├── Cache.php
│   ├── CacheEngine.php
│   ├── CacheRegistry.php
│   ├── Engine
│   │   ├── ApcEngine.php
│   │   ├── FileEngine.php
│   │   ├── MemcachedEngine.php
│   │   ├── NullEngine.php
│   │   ├── RedisEngine.php
│   │   ├── WincacheEngine.php
│   │   └── XcacheEngine.php
│   ├── README.md
│   └── composer.json
...
├── View
│   ├── AjaxView.php
│   ├── Cell.php
│   ├── CellTrait.php
│   ├── Exception
│   │   ├── MissingCellException.php
│   │   ├── MissingCellViewException.php
│   │   ├── MissingElementException.php
│   │   ├── MissingHelperException.php
│   │   ├── MissingLayoutException.php
│   │   ├── MissingTemplateException.php
│   │   └── MissingViewException.php
│   ├── Form
│   │   ├── ArrayContext.php
│   │   ├── ContextInterface.php
│   │   ├── EntityContext.php
│   │   ├── FormContext.php
│   │   └── NullContext.php
│   ├── Helper
│   │   ├── FlashHelper.php
│   │   ├── FormHelper.php
│   │   ├── HtmlHelper.php
│   │   ├── IdGeneratorTrait.php
│   │   ├── NumberHelper.php
│   │   ├── PaginatorHelper.php
│   │   ├── RssHelper.php
│   │   ├── SecureFieldTokenTrait.php
│   │   ├── SessionHelper.php
│   │   ├── TextHelper.php
│   │   ├── TimeHelper.php
│   │   └── UrlHelper.php
│   ├── Helper.php
│   ├── HelperRegistry.php
│   ├── JsonView.php
│   ├── SerializedView.php
│   ├── StringTemplate.php
│   ├── StringTemplateTrait.php
│   ├── View.php
│   ├── ViewBlock.php
│   ├── ViewBuilder.php
│   ├── ViewVarsTrait.php
│   ├── Widget
│   │   ├── BasicWidget.php
│   │   ├── ButtonWidget.php
│   │   ├── CheckboxWidget.php
│   │   ├── DateTimeWidget.php
│   │   ├── FileWidget.php
│   │   ├── LabelWidget.php
│   │   ├── MultiCheckboxWidget.php
│   │   ├── NestingLabelWidget.php
│   │   ├── RadioWidget.php
│   │   ├── SelectBoxWidget.php
│   │   ├── TextareaWidget.php
│   │   ├── WidgetInterface.php
│   │   └── WidgetRegistry.php
│   └── XmlView.php
└── basics.php
```

So I prepare the `.ac-php-conf.json` like following at project root.

``` json
{
  "use-cscope": false,
  "filter": {
    "php-file-ext-list": [
      "php"
    ],
    "php-path-list": [
      "./vendor/cakephp/cakephp/src"
    ],
    "php-path-list-without-subdir": []
  }
}
```

And I executed `M-x ac-php-remake-tags-all`, but the error like following was occurred.

``` shell
do remake /path/to/cakephp/project/
 REBUILD: load file  modify time  start
 REBUILD:  rebuild file start
ERROR ----- 
````

As a test, I modified `.ac-php-conf.json` like following and execute command once again, build was succeeded.

``` json
{
  "use-cscope": false,
  "filter": {
    "php-file-ext-list": [
      "php"
    ],
    "php-path-list": [
      "./vendor/cakephp/cakephp/src/Auth" // <-- modified here
    ],
    "php-path-list-without-subdir": []
  }
}
```

I have thought the reason of fail is `./vendor/cakephp/cakphp/src` contains only sub-directories. But there is `basics.php`. Then, why build on `./vendor/cakephp/cakephp/src` was failed and build on `./vendor/cakephp/cakephp/src/Auth` was succeeded?

I assume that the build may success if set the sub-directories of `vendor/cakephp/cakephp/src` to `php-path-list` in `.ac-php-conf.json`. But It takes some times and effort. 
Is there any good way?

**Comment by tasuwo** [comment]
I tried following.

> I assume that the build may success if set the sub-directories of vendor/cakephp/cakephp/src to php-path-list in .ac-php-conf.json.

As a result, when configuration file contains some directories, build was failed. The directories are following.

- ./vendor/cakephp/cakephp/src/Collection
- ./vendor/cakephp/cakephp/src/Core
- ./vendor/cakephp/cakephp/src/I18n

And directory tree's are following.

``` shell
Collection
├── Collection.php
├── CollectionInterface.php
├── CollectionTrait.php
├── ExtractTrait.php
├── Iterator
│   ├── BufferedIterator.php
│   ├── ExtractIterator.php
│   ├── FilterIterator.php
│   ├── InsertIterator.php
│   ├── MapReduce.php
│   ├── NestIterator.php
│   ├── NoChildrenIterator.php
│   ├── ReplaceIterator.php
│   ├── SortIterator.php
│   ├── StoppableIterator.php
│   ├── TreeIterator.php
│   ├── TreePrinter.php
│   ├── UnfoldIterator.php
│   └── ZipIterator.php
├── LICENSE.txt
├── README.md
├── composer.json
└── functions.php
```

``` shell
Core
├── App.php
├── ClassLoader.php
├── Configure
│   ├── ConfigEngineInterface.php
│   ├── Engine
│   │   ├── IniConfig.php
│   │   ├── JsonConfig.php
│   │   └── PhpConfig.php
│   └── FileConfigTrait.php
├── Configure.php
├── ConventionsTrait.php
├── Exception
│   ├── Exception.php
│   └── MissingPluginException.php
├── InstanceConfigTrait.php
├── LICENSE.txt
├── ObjectRegistry.php
├── Plugin.php
├── README.md
├── StaticConfigTrait.php
├── composer.json
└── functions.php
```

``` shell
I18n
├── ChainMessagesLoader.php
├── Date.php
├── DateFormatTrait.php
├── Formatter
│   ├── IcuFormatter.php
│   └── SprintfFormatter.php
├── FrozenDate.php
├── FrozenTime.php
├── I18n.php
├── LICENSE.txt
├── MessagesFileLoader.php
├── Middleware
│   └── LocaleSelectorMiddleware.php
├── Number.php
├── Parser
│   ├── MoFileParser.php
│   └── PoFileParser.php
├── PluralRules.php
├── README.md
├── RelativeTimeFormatter.php
├── Time.php
├── TranslatorRegistry.php
├── composer.json
└── functions.php
```

**Comment by xcwen** [comment]
you need find which php file make it fail

**Comment by tasuwo** [comment]
I found the php files which are a couse of failing. The files are `functions.php`.

- [Core/functions.php](https://github.com/cakephp/cakephp/blob/master/src/Core/functions.php)
- [I18n/funcitons.php](https://github.com/cakephp/cakephp/blob/master/src/I18n/functions.php)
- [Collection/functions.php](https://github.com/cakephp/cakephp/blob/master/src/Collection/functions.php)

I tried `phpctags` command in `ac-php-core` for `function.php` with `--debug` option and got logs as following.

```
11% /Users/tasuwo/workspace/cakephp-app/vendor/cakephp/cakephp/src/Collection/functions.php
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function PHPCtags::func_get_return_type(), 1 passed in phar:///Users/tasuwo/.emacs.d/.cask/25.1/elpa/ac-php-core-20160819.2147/phpctags/PHPCtags.class.php on line 434 and exactly 2 expected in phar:///Users/tozawa/.emacs.d/.cask/25.1/elpa/ac-php-core-20160819.2147/phpctags/PHPCtags.class.php:163
Stack trace:
#0 phar:///Users/tasuwo/.emacs.d/.cask/25.1/elpa/ac-php-core-20160819.2147/phpctags/PHPCtags.class.php(434): PHPCtags->func_get_return_type(Object(PhpParser\Node\Stmt\Function_))
#1 phar:///Users/tasuwo/.emacs.d/.cask/25.1/elpa/ac-php-core-20160819.2147/phpctags/PHPCtags.class.php(198): PHPCtags->struct(Object(PhpParser\Node\Stmt\Function_))
#2 phar:///Users/tasuwo/.emacs.d/.cask/25.1/elpa/ac-php-core-20160819.2147/phpctags/PHPCtags.class.php(391): PHPCtags->struct(Array)
#3 phar:///Users/tasuwo/.emacs.d/.cask/25.1/elpa/ac-php-core-20160819.2147/phpctags/PHPCtags.class.php(198): PHPCtags->struct(Object(PhpParser\Node\Stmt\If_))
#4 phar:///Users/tasuwo/.ema in phar:///Users/tozawa/.emacs.d/.cask/25.1/elpa/ac-php-core-20160819.2147/phpctags/PHPCtags.class.php on line 163

Fatal error: Uncaught ArgumentCountError: Too few arguments to function PHPCtags::func_get_return_type(), 1 passed in phar:///Users/tasuwo/.emacs.d/.cask/25.1/elpa/ac-php-core-20160819.2147/phpctags/PHPCtags.class.php on line 434 and exactly 2 expected in phar:///Users/tozawa/.emacs.d/.cask/25.1/elpa/ac-php-core-20160819.2147/phpctags/PHPCtags.class.php:163
Stack trace:
#0 phar:///Users/tasuwo/.emacs.d/.cask/25.1/elpa/ac-php-core-20160819.2147/phpctags/PHPCtags.class.php(434): PHPCtags->func_get_return_type(Object(PhpParser\Node\Stmt\Function_))
#1 phar:///Users/tasuwo/.emacs.d/.cask/25.1/elpa/ac-php-core-20160819.2147/phpctags/PHPCtags.class.php(198): PHPCtags->struct(Object(PhpParser\Node\Stmt\Function_))
#2 phar:///Users/tasuwo/.emacs.d/.cask/25.1/elpa/ac-php-core-20160819.2147/phpctags/PHPCtags.class.php(391): PHPCtags->struct(Array)
#3 phar:///Users/tasuwo/.emacs.d/.cask/25.1/elpa/ac-php-core-20160819.2147/phpctags/PHPCtags.class.php(198): PHPCtags->struct(Object(PhpParser\Node\Stmt\If_))
#4 phar:///Users/tasuwo/.ema in phar:///Users/tozawa/.emacs.d/.cask/25.1/elpa/ac-php-core-20160819.2147/phpctags/PHPCtags.class.php on line 163
```

I think this seems like a problem of phpctags (https://github.com/xcwen/phpctags).
I tried to fix this problem, but I don't know how to build `phpctags` of this repository from [this](https://github.com/xcwen/phpctags).

**Comment by xcwen** [comment]
thanks . i try it.

**Comment by xcwen** [comment]
retest .

**Comment by tasuwo** [comment]
Got worked! Thanks!

**Comment by xcwen** [comment]
you need update again :<

**Comment by tasuwo** [comment]
Does your comment "update again" means "update ac-php repository and test again" ?
Did it, and I confirmed that the build by `ac-php-remake-tags-all` command not failed.
I'm sorry if I'm misunderstand.

**Comment by xcwen** [comment]
phpctags  now is ok .

**Comment by tasuwo** [comment]
OK, thanks for fix of phpctags, this issue seems like be solved.
I tried phpctags with `--debug` option again, confirmed that it works well for `functions.php`, and I could build cakephp project's tags by `ac-php-remake-tags-all` command with no fail.
Thanks very much!
